version: "3.8"
services:
  
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - logs:/app/logs
      - ./backend/images:/app/images
      - ./backend:/app
      - /app/node_modules
      

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: